import Head from "next/head";
import { Inter } from "next/font/google";
import Homescreen from "../../components/Homescreen";
import Header from "../../components/Header";
import About from "../../components/About";
import Jobs from "../../components/Jobs";
import Contact from "../../components/Contact";
import Footer from "../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        {/* navigation */}
        <Header />
        {/* screens */}
        <Homescreen />
        <About />
        <Jobs />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
